### ISSUE TITLE
unexpected behavior when using a binding form pattern with redex-match

### ISSUE THREAD

**Issue by howell** [racket/redex#98]
I don't understand why, but using the binding declaration gives me unexpected behavior with pattern matching. Removing the binding declaration is enough to get back to the behavior I expected. I haven't found anything in the documentation to explain the difference.

 A pared down example illustrating this:

```
#lang racket

(require redex)

(define-language typed-syndicate
  (S hello)
  (P ★)
  (l (λ (P S)))
  #:binding-forms
  (λ (P S #:refers-to P) ...))

(redex-match? typed-syndicate (λ P S) (term (λ ★ hello)))
;; #t
(redex-match? typed-syndicate (λ (P S)) (term (λ (★ hello))))
;; #f (why?)
```

**Comment by rfindler** [comment]
I think that probably this is the result of a missing error check (that I'm not sure how to do). I believe the issue here is that redex feels free to assume that if some symbol matches a non-terminal and that non-terminal is used after a `#:refers-to`, then it assumes it can stick stuff onto the end of it and get another symbol that would also match, in this case, `P`.

Taking this thought and adapting your example, this produces two `#t`s

```
#lang racket

(require redex)

(define-language typed-syndicate
  (S hello)
  (P (variable-prefix ★))
  (l (λ (P S)))
  #:binding-forms
  (λ (P S #:refers-to P) ...))

(redex-match? typed-syndicate (λ P S) (term (λ ★ hello)))
(redex-match? typed-syndicate (λ (P S)) (term (λ (★ hello))))
```

**Comment by howell** [comment]
So if I understand what you're saying, when a symbol appears in a binding position Redex isn't sensitive to whether that symbol is a keyword or a variable, treating both cases like a variable.

This is an issue for my use case; I have patterns and want to include a 'match anything pattern' (that's what the `★` was being used for).  I can work around this though by using `(★)` where I would have just written `★`:

```racket
#lang racket

(require redex)

(define-language typed-syndicate
  (S hello)
  (P (★) (P ...))
  (l (λ (P S)))
  #:binding-forms
  (P ...) #:exports (shadow P ...)
  (λ (P S #:refers-to P) ...))

(redex-match? typed-syndicate (λ P S) (term (λ (★) hello)))
;; #t
(redex-match? typed-syndicate (λ (P S)) (term (λ ((★) hello))))
;; #t
```

I thought that I might also be able to work around this behavior by adding a `★ #:exports nothing` clause but Redex doesn't accept that as valid.

(I also just understood what you were getting at, if I use the pattern `(variable-prefix ★)` throughout my model in place of `★` I will get the expected behavior as well and can still more-or-less treat `★` as a keyword).

**Comment by rfindler** [comment]
I wouldn't phrase it as "when a symbol appears in a binding position Redex isn't sensitive to whether that symbol is a keyword or a variable", more like "things that are binders are supposed to be variables" and then that forms the justification for various internal choices.

But I may be missing something here still: why do you have a `#:refers-to` with something that isn't a variable? Can you supply a model that still isn't your full model, but that has a little bit more going on to explain that choice?

**Comment by howell** [comment]
ok, here's an example of how I wound up with a symbol that appears in a binding position but is not a variable:

```racket
#lang racket

(require redex)

(define-language L
  (e (e e) X b (p e ...) (λ (P e) ...) (tuple e ...))
  (b number)
  (p +)
  (P ★              ;; match anything
     (bind X)       ;; bind X
     (= X)          ;; match things that are equal to the value bound to X
     b (p e ...)    ;; match with equality
     (tuplep P ...) ;; match recursively
     )
  (X variable-not-otherwise-mentioned)
  #:binding-forms
  (bind X) #:exports X
  (= X) #:exports nothing
  (tuplep P ...) #:exports (shadow P ...)
  (λ (P e #:refers-to P) ...))

(redex-match? L (λ P e) (term (λ ★ 0)))
;; #t
(redex-match? L (λ (P e)) (term (λ (★ 0))))
;; #f
```

**Comment by rfindler** [comment]
Oh! I see what you mean now. Yes, I agree that it would be nice if one could write `★ #:exports nothing` instead of `(★) #:exports nothing`.

Probably best to just stick the extra parens in for now.

**Comment by wilbowma** [comment]
Isn't this the same problem as #62?

**Comment by howell** [comment]
@wilbowma oh yeah, you're right.

**Comment by wilbowma** [comment]
:P I've been studying the issues with binding and patterns, and noticing .. patterns.

**Comment by rfindler** [comment]
@howell I had completely forgotten about that other issue that @florence opened and that @paulstansifer had commented on. I think my reply over there was more useful than my reply here. :)

**Comment by rfindler** [comment]
I don't know if the commit I just pushed (19f48d2e94a848dd2bfd533eceb79a0b5f5ed361) solves the original problem in this PR. If @howell / @wilbowma would have a look, that'd be appreciated.

**Comment by wilbowma** [comment]
Looks like both of @howell's examples, and @florence's example from #62; is there a reason they aren't added to the test suite? (It's not immediately clear to me that the these and the new test are redundant)

**Comment by wilbowma** [comment]
This is unrelated, but matcher.rkt line 135, why is the `lang-α-equal?` parameter of `build-compiled-pattern` set to `equal?`? (I don't really understand compiled languages and patterns, so maybe it ought to be, but I'd expect something more .. sophisticated, as in line 692)

**Comment by wilbowma** [comment]
Okay, looks good to me. All the examples in here and #62 pass now (except mine from #62, which we found was an unrelated problem), and the test suite passes. I looked over the code and it looks like a straightforward change, and I can't find any places you missed.

**Comment by rfindler** [comment]
Thank you for checking over the commit!

As for line 135, I am not sure, but I think that it cannot affect the results of matching, only the performance, and I cannot tell if it would be a win or a lose to do the alpha-equal comparison. In particular, that function is called to drop duplicate matches and those patterns are the ones that appear inside a `define-language` expression. Patterns inside a `define-language` are always inside non-terminals, so duplicates are going to get dropped at the point where that match happens. Hm. Unless it is a decomposition, tho. So I guess I'm not sure. It might be possible to formulate a test case. If you have the energy to give it a try, that'd be welcome. 

But while looking into this, I noticed the use of `equal?` inside `remove-bindings/filter` that I also couldn't formulate a test case for, but seems uncontroversially wrong.

I'll close the two issues now. Feel free to reopen if I'm missing something in the discussion that the commits don't address.
